version: "3"
networks:
  notary-endpoint-test:
services:
  kafka:
    image: spotify/kafka
    networks:
      - notary-endpoint-test
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: "9092"
  ethereum-service-mock:
    build: ./ethereum-service-mock
    networks:
      - notary-endpoint-test
  notary-endpoint:
    build: ./.
    ports:
      - 8000:8000
    networks:
      - notary-endpoint-test
    environment:
      KAFKA_BROKERS: kafka:9092
      REQUEST_TOPIC: request
      RESPONSE_TOPIC: response
      ERROR_TOPIC: error
      RUST_LOG: "ubirch_notary_endpoint=debug,warp=debug,rdkafka=debug"
      KAFKA_DEBUG: "broker,msg,consumer"
      EXPLORER_URL: some-eth-explorer
      BIND_ADDR: "0.0.0.0:8000"
    entrypoint:
      - bash
      - -c
      - "sleep 5s && ./ubirch-notary-endpoint"