# Default values for notary service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ubirch/ubirch-notary-endpoint
  tag: latest
  pullPolicy: Always

service:
  name: notary-service
  type: ClusterIP
  port: 80

ingress:
  enabled: enable
  annotations:
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
    certmanager.k8s.io/acme-dns01-provider: "dnsprovider"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: notary-service-httpauth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  path: /
  hosts:
    - notary.domain.tld
  tls:
    - secretName: notary-certificate
      hosts:
        - notary.domain.tld

notaryService:
  kafkaBrokers: "kafkaserverver:9092"
  kafkaDebug: "broker"
  request: "com.ubirch.ethereum.input.bin"
  response: "com.ubirch.ethereum.output.json"
  error: "com.ubirch.ethereum.errors.json"
  explorer: "https://rinkeby.etherscan.io/tx"
  httpauth: "user:htpasswd"
  rustlog: "ubirch_notary_endpoint=debug,warp=debug,rdkafka=debug"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 2
   memory: 4Gi
  requests:
   cpu: 1
   memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
